- !!python/object/apply:tensorflow.keras.callbacks.ModelCheckpoint
  kwds:
    filepath: !join [$base_path, !datetime '/mcp/{now:%Y%m%d-%H%M%S}']
    monitor:  val_loss
    mode: auto
    verbose: 0
    save_best_only: true
    save_weights_only: true
- !!python/object/apply:tensorflow.keras.callbacks.EarlyStopping
    kwds:
      monitor: val_loss
      mode: auto
      patience: 8
      verbose: 0
- !!python/object/apply:tensorflow.keras.callbacks.ReduceLROnPlateau
    kwds:
      monitor: val_loss
      mode: auto
      patience: 2
      verbose: 0
     # min_delta: 0.1
      factor: 0.1
      min_lr: !product [$lr, 0.00001]
- !!python/object/apply:tensorflow.keras.callbacks.CSVLogger
    kwds:
      filename: !join [$base_path, !datetime '/{now:%Y%m%d-%H%M%S}.csv']
      append: false