data_path: ../paper_data
history_size: !store [history_size, !product [48,7,2]]
prediction_size: !store [horizon_size, !product [48,1]]
shift: $horizon_size
history_columns:  ['load']
meta_columns: ['dayofyear_sin', 'dayofyear_cos', 'weekday', 'time_sin', 'time_cos', 'is_holiday']
prediction_columns: ['load']
validation_split: 0.1
batch_size: 32
cycle_length: 10
shuffle_buffer_size: 100
seed: $seed