data_path: ../data/CER Electricity Revised March 2012/preprocessed/mini
history_size: !store [history_size, !product [48,7]]
horizon_size: !store [horizon_size, !product [48,1]]
shift: $horizon_size
historic_columns: ['load', 'is_holiday', 'tempC']
horizon_columns: ['is_holiday', 'tempC']
prediction_columns: ['load']
validation_split: 0.1
batch_size: 32
cycle_length: 10
shuffle_buffer_size: 100
seed: $seed